apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  labels:
    app: policy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: indikak2005/policy-service:406283282a7798cf4270c64266fa8eeb4f06dfc1
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8082
