apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  labels:
    app: policy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: indikak2005/policy-service:a9e48e8d4fb16bde4050881cb9f6eb0936ecb8fb
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8082
